# Step 1: Use the SDK to build the code
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the project file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Step 2: Use the Runtime to run the code (makes the image small)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

# Tell Docker which port the app runs on
EXPOSE 80
ENTRYPOINT ["dotnet", "user-service.dll"] 
# ^ Change "user-service.dll" to match the project name for Auth and Gateway